fix: refatoração para utilização dos dados inseridos no mongodb.
tekpixo/moba.aid pull request #35
Opened 2020-02-26 20:31 UTC by tekpixo

2020-02-26 22:38 UTC, santospatrick requested changes

2020-02-26 22:38 UTC, santospatrick commented on server/app/controllers/ChampionController.js
> +            champions = await Champion.findOne({ id_ddragon });
Assim, por enquanto não tem tanto problema, mas é bom ter 1 método pra buscar a lista e 1 método pra buscar por ID, principalmente pq os filtros vão ser diferentes, a quantidade de atributos da lista não precisa ser a mesma de quando buscamos por id também.

2020-02-26 22:41 UTC, tekpixo commented on server/app/controllers/ChampionController.js
> +            champions = await Champion.findOne({ id_ddragon });
Maneiro, eu também tinha ficado incomodado com isso aí. Tem alguma padronização de como seria esse método usado pra buscas? Ficaria nessa mesma controller ou criamos uma específica?

2020-02-27 01:11 UTC, santospatrick commented on server/app/controllers/ChampionController.js
> +            champions = await Champion.findOne({ id_ddragon });
Acho que não tem um super padrão não haha só um outro método mesmo sla `list()`

2020-02-27 01:16 UTC, merged